PSP_BEGIN_EXPORTS 

PSP_EXPORT_START(syslib, 0, 0x8000) 
PSP_EXPORT_FUNC(module_start) 
PSP_EXPORT_VAR(module_info) 
PSP_EXPORT_END 

PSP_EXPORT_START(input_util, 0, 0x8001) 
PSP_EXPORT_FUNC(inputUpdate) 
PSP_EXPORT_FUNC(inputIsButtonDown) 
PSP_EXPORT_FUNC(inputIsButtonUp) 
PSP_EXPORT_FUNC(inputIsButtonPressed) 
PSP_EXPORT_FUNC(inputIsButtonReleased) 
PSP_EXPORT_FUNC(inputGetCurrent) 
PSP_EXPORT_FUNC(inputGetPrev) 
PSP_EXPORT_END 

PSP_END_EXPORTS 
